site = "https://clawpage.yelo.ooo"
public_dir = "public"
out_dir = "dist"

[template.options]
title = "clawpage"
subtitle = "demo for clawpage (shareable static chat archive)"
description = "Clawpage - A place for sharing and exploring AI chat conversations."
footer = "powered by [@imyelo](https://github.com/imyelo) &times; [@lambda610](https://github.com/lambda610)"

[template.options.analytics]
google_analytics_id = "G-XKZDFTDC4R"

[template.options.promo]
enabled = true
